---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-server
  name: api-server
  namespace: demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: api-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    run: api-server
  name: api-server
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: api-server
      name: api-server
    spec:
      containers:
      - args:
        - /bin/bash
        image: nvbeta//api_server
        imagePullPolicy: Always
        name: api-server
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
